stages:
  - analyze
  - test

analyzer:
  image: bash:5.2.15
  stage: analyze
  before_script:
    - pwd
    - vim --version
    - date
  script:
    - time
    - echo "Flutterdam sample script"
    - sleep 35
    - echo "35 done"
    - sleep 35
    - echo "sleep done"
    - mkdir gago
    - touch gago/info.txt
  artifacts:
    untracked: false
    expire_in: 1 days
    paths:
      - gago/
  tags:
    - "dev"
lolomo:
  stage: test
  script:
    - test -f "gago/info.txt"
    - time
  tags:
    - "dev"
ios:
  stage: ios
  script:
    - open -a Simulator.app
    - fvm flutter run
  tags:
    - "dev"

